server:
  port: 8091
spring:
  data:
    mongodb:
      username: adaptive
      password: adaptive1234
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin